-- MySQL Script generated by MySQL Workbench
-- Thu May 14 00:14:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academicoll
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academicoll
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academicoll` DEFAULT CHARACTER SET utf8 ;
USE `academicoll` ;

-- -----------------------------------------------------
-- Table `academicoll`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academicoll`.`aluno` ;

CREATE TABLE IF NOT EXISTS `academicoll`.`aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(100) NOT NULL,
  `emailAluno` VARCHAR(100) NOT NULL,
  `telAluno` CHAR(10) NOT NULL,
  `cepAluno` CHAR(8) NOT NULL,
  `ruaAluno` VARCHAR(150) NOT NULL,
  `numAluno` INT NOT NULL,
  `bairroAluno` VARCHAR(60) NOT NULL,
  `cidadeAluno` VARCHAR(60) NOT NULL,
  `estadoAluno` CHAR(2) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;

ALTER TABLE `academicoll`.`aluno`
AUTO_INCREMENT = 222222;

-- -----------------------------------------------------
-- Table `academicoll`.`disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academicoll`.`disciplina` ;

CREATE TABLE IF NOT EXISTS `academicoll`.`disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `nomeDisciplina` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;

ALTER TABLE `academicoll`.`disciplina`
AUTO_INCREMENT = 1111;
-- -----------------------------------------------------
-- Table `academicoll`.`aluno_has_disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academicoll`.`aluno_has_disciplina` ;

CREATE TABLE IF NOT EXISTS `academicoll`.`aluno_has_disciplina` (
  `idAluno` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  `nota1` INT ZEROFILL NULL,
  `nota2` INT ZEROFILL NULL,
  `nota3` INT ZEROFILL NULL,
  `media` DECIMAL(10,2) ZEROFILL NULL,
  `conceito` CHAR(1) NULL,
  PRIMARY KEY (`idAluno`, `idDisciplina`),
  INDEX `fk_aluno_has_disciplina_disciplina1_idx` (`idDisciplina` ASC),
  INDEX `fk_aluno_has_disciplina_aluno_idx` (`idAluno` ASC),
  CONSTRAINT `fk_aluno_has_disciplina_aluno`
    FOREIGN KEY (`idAluno`)
    REFERENCES `academicoll`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_disciplina_disciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `academicoll`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
